[package]
name = "guessing_game"
version = "0.1.0"
authors = ["Tom Monks <t.m.w.monks@exeter.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"