[package]
name = "enum_exercise"
version = "0.1.0"
authors = ["Tom Monks <thomas.m.monks@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
